### ISSUE TITLE
Unkown OBIS value

### ISSUE THREAD

**Issue by thgonline** [iobroker-community-adapters/ioBroker.sma-em#137]
Hallo,

ich bekomme alle 30 Minuten folgende Warnung:

`
sma-em.0 | 2021-03-05 22:53:45.261 | warn | (5260) Unkown OBIS value 7401228 found in UDP packet. Skip it and going to the next OBIS value.
-- | -- | -- | --
sma-em.0 | 2021-03-05 22:53:45.261 | warn | (5260) Unkown OBIS value 4194304 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:45.260 | warn | (5260) Unkown OBIS value 3195048 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:45.259 | warn | (5260) Unkown OBIS value 2097152 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:40.419 | warn | (5260) Unkown OBIS value 7401228 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:40.418 | warn | (5260) Unkown OBIS value 4194304 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:40.418 | warn | (5260) Unkown OBIS value 3195048 found in UDP packet. Skip it and going to the next OBIS value.
sma-em.0 | 2021-03-05 22:53:40.418 | warn | (5260) Unkown OBIS value 2097152 found in UDP packet. Skip it and going to the next OBIS value.
`

Was kann das sein?

**Comment by pdbjjens** [comment]
@thgonline 
Ein Screenshot des expandierten Objects-tree von sma-em.0 sowie eine Beschreibung der Umgebung (SMA-EM oder  SHM, wie viele, Firmwareversionen SEM oder SHM, SMA-EM Adapter Version, Besonderheiten der Netzwerkstruktur (VLAN, DMZ etc), sonstige SMA-Geräte im Netzwerk ) wäre hilfreich für die Analyse. Auch das iobroker log vom Adapter start könnte helfen.
Tritt das Problem regelmäßig alle halbe Stunde auf? 
Sind es dann immer die oben gezeigten 8 Meldungen mit denselben OBIS Werten?

**Comment by fspitzb** [comment]
Ich habe das gleiche Problem. Seit einem Zeitpunkt, den ich nicht genau eingrenzen kann, bekomme ich jede Minute eine Fehlermeldung. Das ist eine alte Installation, die seit Monaten unverändert läuft.
Auf einer einer neuen Installation (aktueller ioBroker mit aktuellem em-Adapter) wirft mich auch mit den o.g. Fehlern zu, Dabei fällt mir auf, dass ein zweites Gerät mit einer mir unbekannten SN angezeigt wird. Auf der neuen Installation wird der Adapter dann irgendwann wegen Restart-Loop beendet.
Vielleicht hilft es, die Serient-Nr. in die Konfiguration aufzunehmen und alle Datenpakete zu ignorieren, die nicht von der Serien-Nr kommen.

Falk

**Comment by pdbjjens** [comment]
@fspitzb 
Ich habe den Verdacht, dass die o.g. warnings vom SMA Device Discovery herrühren. Das basiert ebenfalls auf multicast. In der Response meldet sich ein SMA Gerät mit einem multicast datagram. Ist es Dir möglich, das erwähnte zweite SMA-Gerät (vermutlich ein Wechselrichter) anhand der Seriennummer zu identifizieren? Wird es vom SMA-Adapter im Objekt-Baum angelegt? Ein screenshot davon wäre hilfreich, ebenso eine Auszug aus dem log mit den warnings so wie aller anderen Meldungen die damit zu tun haben könnten insbesondere vom Start des Adapters und dessen Beendigung durch iobroker.

**Comment by fspitzb** [comment]
Die Seriennr. hat keins meiner SMA-Geräte. Hätte mich auch sehr gewundert, weil die Anlage seit 6 Jahren unverändert läuft.

Meldungen vom Start des Adapters bis zum 1. Absturz
Das wiederholt sich im Abstand von 1 Minute, bis ioBroker die Nase voll hat
und den Adapter nicht neu startet.

2021-04-01 14:51:51.284 - info: host.JoomlaTest "system.adapter.sma-em.0" enabled
2021-04-01 14:51:51.294 - info: host.JoomlaTest instance system.adapter.sma-em.0 started with pid 4668
2021-04-01 14:51:51.679 - info: sma-em.0 (4668) starting. Version 0.6.3 in /opt/iobroker/node_modules/iobroker.sma-em, node: v12.22.0, js-controller: 3.2.16
2021-04-01 14:51:51.703 - info: sma-em.0 (4668) Details L1 false Details L2 false Details L3 false Extended info false
2021-04-01 14:51:51.704 - info: sma-em.0 (4668) Listen via UDP on Device enp0s3 with IP 192.168.28.84 on Port 9522 for Multicast IP 239.12.255.254
2021-04-01 14:52:04.641 - error: sma-em.0 (4668) uncaught exception: The value of "offset" is out of range. It must be >= 0 and <= 16. Received 20
2021-04-01 14:52:04.643 - error: sma-em.0 (4668) RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 16. Received 20
at boundsError (internal/buffer.js:82:9)
at Uint8Array.readUInt32BE (internal/buffer.js:305:5)
at Uint8Array.readUIntBE (internal/buffer.js:263:17)
at Socket. (/opt/iobroker/node_modules/iobroker.sma-em/main.js:184:24)
at Socket.emit (events.js:314:20)
at UDP.onMessage [as onmessage] (dgram.js:921:8)
2021-04-01 14:52:04.644 - error: sma-em.0 (4668) Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 16. Received 20
2021-04-01 14:52:04.663 - warn: sma-em.0 (4668) Unkown OBIS value 2097152 found in UDP packet. Skip it and going to the next OBIS value.
2021-04-01 14:52:04.663 - warn: sma-em.0 (4668) Unkown OBIS value 3195048 found in UDP packet. Skip it and going to the next OBIS value.
2021-04-01 14:52:04.664 - warn: sma-em.0 (4668) Unkown OBIS value 4194304 found in UDP packet. Skip it and going to the next OBIS value.
2021-04-01 14:52:04.664 - warn: sma-em.0 (4668) Unkown OBIS value 7401228 found in UDP packet. Skip it and going to the next OBIS value.
2021-04-01 14:52:04.665 - info: sma-em.0 (4668) cleaned everything up...
2021-04-01 14:52:04.666 - info: sma-em.0 (4668) terminating
2021-04-01 14:52:04.666 - warn: sma-em.0 (4668) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-01 14:52:05.169 - warn: sma-em.0 (4668) get state error: Connection is closed.
2021-04-01 14:52:05.169 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.169 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.170 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.170 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.170 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.170 - warn: sma-em.0 (4668) get state error: DB closed
2021-04-01 14:52:05.172 - warn: sma-em.0 (4668) get state error: Connection is closed.
2021-04-01 14:52:05.190 - error: host.JoomlaTest instance system.adapter.sma-em.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-01 14:52:05.190 - info: host.JoomlaTest Restart adapter system.adapter.sma-em.0 because enabled

Einen Screenshot des Objekts mit der ungültigen SN habe ich angehängt
![emadapter](https://user-images.githubusercontent.com/81752363/113297577-0f88c400-92fb-11eb-8ee5-ac0480749662.png)

**Comment by fspitzb** [comment]
Ganz unten im Screenshot mit der Nr. 1900211981 das "echte" em.

**Comment by pdbjjens** [comment]
Welche Firmware Version hat der SMA Energy Meter? Traten die warnings erst mit der Version 0.6.x des Adapters auf oder schon vorher?

**Comment by fspitzb** [comment]
Firmware des EM ist 1.02.04. Die Fehler treten auch mit dem Adapter 0.5.7 auf. Diese Kombination lief letzten Sommer aber noch fehlerfrei. 
Die Datenpakete, die den Adapter durcheinander bringen kommen bestimmt von einem anderen Gerät im Netzwerk, ich habe nur keinen Schimmer von welchem. Es liegt bestimmt nicht an der Kombination von EM und Adapter (wie gesagt die lief monatelang fehlerfrei ohne das am ioBroker/Adapter/EMeter etwas verändert wurde)

Das Ganze hatte über den Winter Pause, als ich den Rechner mit dem ioBroker dann vor ein paar Wochen wieder angeworfen habe, habe ich die Fehler schon beobachtet, allerdings nichts unternommen, weil es funktionierte.

Kannst du die Fehler nicht abfangen, so dass der Adapter nicht mehr abstürzt?

Falk

**Comment by thgonline** [comment]
@pdbjjens 

Ich habe deine Frage im iobroker Forum beantwortet.

Bis vor wenigen Wochen lief es bei mir auch ohne Probleme aber nach irgendeinem Update node.js, Java, SMA EM oder oder kamen die Warnungen.

**Comment by pdbjjens** [comment]
@thgonline @fspitzb 
Issue is fixed with release v0.6.4.
