### ISSUE TITLE
Node.js Version 10 not working

### ISSUE THREAD

**Issue by andiling** [iobroker-community-adapters/ioBroker.sma-em#17]
sma-em.0 | 2018-08-09 13:03:11.016 | error | at UDP.onMessage [as onmessage] (dgram.js:643:8)
-- | -- | -- | --
sma-em.0 | 2018-08-09 13:03:11.016 | error | at Socket.emit (events.js:182:13)
sma-em.0 | 2018-08-09 13:03:11.016 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sma-em/main.js:69:35)
sma-em.0 | 2018-08-09 13:03:11.016 | error | at Uint8Array.readUIntBE (internal/buffer.js:162:3)
sma-em.0 | 2018-08-09 13:03:11.016 | error | at boundsError (internal/buffer.js:55:9)
sma-em.0 | 2018-08-09 13:03:11.016 | error | RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
sma-em.0 | 2018-08-09 13:03:11.015 | error | uncaught exception: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
sma-em.0 | 2018-08-09 13:03:10.331 | info | Details L1 true Details L2 true Details L3 true
sma-em.0 | 2018-08-09 13:03:10.331 | info | Listen via UDP on Port 9522 for Multicast IP 239.12.255.254
sma-em.0 | 2018-08-09 13:03:10.325 | info | starting. Version 0.5.3 in /opt/iobroker/node_modules/iobroker.sma-em, node: v10.8.0

**Comment by gbdeining** [comment]
I solved the problem by installing the current Node.js (11).
[https://nodejs.org/en/download/current/]

**Comment by HansPeterMeier** [comment]
Bei mir jetzt ebenfalls. Mit 8 war soweit noch alles gut.
`

2019-06-02 20:45:37.051 - info: host.iobroker instance system.adapter.sma-em.0 started with pid 3277
--
2019-06-02 20:45:37.347 - debug: sma-em.0 objectDB connected
2019-06-02 20:45:37.359 - debug: sma-em.0 statesDB connected
2019-06-02 20:45:37.371 - info: sma-em.0 starting. Version 0.5.3 in /opt/iobroker/node_modules/iobroker.sma-em, node: v10.16.0
2019-06-02 20:45:37.389 - info: sma-em.0 Listen via UDP on Port 9522 for Multicast IP 239.12.255.254
2019-06-02 20:45:37.389 - info: sma-em.0 Details L1 false Details L2 false Details L3 false
2019-06-02 20:45:37.903 - error: sma-em.0 uncaught exception: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
2019-06-02 20:45:37.904 - error: sma-em.0 RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
at boundsError (internal/buffer.js:49:9)
at Uint8Array.readUIntBE (internal/buffer.js:156:3)
at Socket. (/opt/iobroker/node_modules/iobroker.sma-em/main.js:69:35)
at Socket.emit (events.js:198:13)
at UDP.onMessage [as onmessage] (dgram.js:628:8)
2019-06-02 20:45:37.904 - info: sma-em.0 cleaned everything up...
2019-06-02 20:45:37.909 - info: sma-em.0 terminating
2019-06-02 20:45:37.941 - error: Caught by controller[0]: RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
2019-06-02 20:45:37.941 - error: Caught by controller[0]: at boundsError (internal/buffer.js:49:9)
2019-06-02 20:45:37.941 - error: Caught by controller[0]: at Uint8Array.readUIntBE (internal/buffer.js:156:3)
2019-06-02 20:45:37.941 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.sma-em/main.js:69:35)
2019-06-02 20:45:37.941 - error: Caught by controller[0]: at Socket.emit (events.js:198:13)
2019-06-02 20:45:37.941 - error: Caught by controller[0]: at UDP.onMessage [as onmessage] (dgram.js:628:8)
2019-06-02 20:45:37.941 - error: host.iobroker instance system.adapter.sma-em.0 terminated with code 0 (OK)
2019-06-02 20:45:37.941 - info: host.iobroker Restart adapter system.adapter.sma-em.0 because enabled


`

**Comment by winni-priel** [comment]
Habe das selbe Problem mit node 10.16 
```
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.964	error	instance system.adapter.sma-em.0 terminated with code 0 (OK)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.964	error	Caught by controller[0]: at UDP.onMessage [as onmessage] (dgram.js:628:8)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.964	error	Caught by controller[0]: at Socket.emit (events.js:198:13)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.964	error	Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sma-em/main.js:69:35)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.963	error	Caught by controller[0]: at Uint8Array.readUIntBE (internal/buffer.js:156:3)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.963	error	Caught by controller[0]: at boundsError (internal/buffer.js:49:9)
host.winni-A68I-350-DELUXE	2019-06-11 17:59:22.963	error	Caught by controller[0]: RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
host.winni-A68I-350-DELUXE	2019-06-11 17:59:20.998	info	instance system.adapter.sma-em.0 started with pid 28875
```

siehe auch im iobroket Forum:
https://forum.iobroker.net/topic/23121/problem-mit-iobroker-sma-em-adapter-nach-node-update

**Comment by Stabilostick** [comment]
Die buffer-checks sind mit Node 10 wohl etwas penibler geworden:

```
buf.readUIntBE(offset, byteLength)

offset <integer> Number of bytes to skip before starting to read. Must satisfy 0 <= offset <= buf.length - byteLength.
byteLength <integer> Number of bytes to read. Must satisfy 0 < byteLength <= 6.
Returns: <integer>
```

Reads byteLength number of bytes from buf at the specified offset and interprets the result as an unsigned integer. Supports up to 48 bits of accuracy.

IMHO nichts mit 8 Bytes lesen, wie im Source Code vorgesehen.

Aber mit Node 12.0.0+: buf.readBigUInt64BE
Da gibts was. :))

**Comment by HansPeterMeier** [comment]
Leider ist der Entwickler nicht mehr zu erreichen. Ich habe testweise mal Node 12 installiert und gegen BigUInt64BE ausgetauscht. Hatte leider nicht den Erfolg. Ich versuch mal mit meinen kleinem Wissen den Adapter im Javascript am laufen zu bekommen, ist dann doch übersichtlicher und einfacher Änderungen zu machen.

**Comment by CTJaeger** [comment]
Ich werde mich in Kürze darum kümmern.

**Comment by winni-priel** [comment]
@CTJaeger, super vielen Dank. Der Adapter ist wirklich klasse, wäre sehr schade wenn er nicht mehr laufen würde.

**Comment by HansPeterMeier** [comment]
Finde den auch super zum lernen. Bekomme nun aus den buffer den Zählerstand, nur ist der ja riesig und lässt sich gerade noch nicht teilen. Glaub den muss ich nochmal konvertieren.

Wenn du da aber dran bist freue ich mich schon auf deine Lösung;-)
Vielleicht kannst du vor der Serial noch von was anhängen? Nur mit Zahlen hat der Admin 3 Probleme oder mein Safari.
Gruß und Danke.

**Comment by andiling** [comment]
Hi, wenn Du keine Zeit hast kannst Du auch den Adapter der Community-Adapter Crew übergeben oder dort selbst beitreten!

https://github.com/iobroker-community-adapters

Gruß Andi

**Comment by CTJaeger** [comment]
Hallo. Werde die Adapter an die Community Adapter Crew übergeben.

**Comment by DutchmanNL** [comment]
1. Go to your GitHub repo that you want to move
2. Change URLs in io-package.json, package.json and README.md form your GitHub repo to Org repo 
3. Settings -> Danger Zone -> Transfer Ownership
4. Click on 'Transfer'
5. Type 'iobroker-community-adapters' as New owner
6. Add the oranization as an owner of your npm packages (npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>)
7. Change the url of your repo via pull req at https://github.com/ioBroker/ioBroker.repositories
8. Thats it

bei fragen am besten mal in unserer telegram Gruppe nachfragen: https://t.me/joinchat/EdtEphZDh1lp4bO8BoYqfA

**Comment by DutchmanNL** [comment]
solved, please use node 12 and ahead
