### ISSUE TITLE
Netzwerkfehler beim Start (EADDRINUSE / Docker)

### ISSUE THREAD

**Issue by ticaki** [iobroker-community-adapters/ioBroker.sma-em#552]
Kopie aus dem iobroker Forum:

Hallo,

der Adapter läuft auch bei mir soweit. Vermissen tue ich den Wert der erzeugten Energie der Solaranlage.

System: Pi 4, bullseye, 

Mein Problem aktuell ist, das ich scrypted in einem Docker Container auf diesem Pi am laufen habe(ist der einzige Container), mich nicht wirklich damit auskenne und dieser erzeugt ein veth device, das sma-em beim Start abbrechen lässt. Ich lösche das Netzwerkgerät aktuell nach einem Reboot manuell und restarte SMA-EM, besser wäre jedoch wenn sma den Fehler behandeln und weiter machen würde.

```
2023-05-07 05:03:37.897 - info: sma-em.0 (4999) starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.0, js-controller: 4.0.24
2023-05-07 05:03:38.039 - info: sma-em.0 (4999) Details L1 false Details L2 false Details L3 false Extended Mode true RealTime Interval 1 non-Realtime Interval 30 Language: de
2023-05-07 05:03:38.042 - info: sma-em.0 (4999) Listen via UDP on Device eth0 with IP 192.168.178.96 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.045 - info: sma-em.0 (4999) Listen via UDP on Device br-e5c20c4ceb49 with IP 172.18.0.1 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.046 - info: sma-em.0 (4999) Listen via UDP on Device veth41362bb with IP 169.254.120.116 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.047 - info: sma-em.0 (4999) Listen via UDP on Device veth41362bb with IP 169.254.246.139 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.053 - error: sma-em.0 (4999) uncaught exception: addMembership EADDRINUSE
2023-05-07 05:03:38.056 - error: sma-em.0 (4999) Error: addMembership EADDRINUSE
at Socket.addMembership (node:dgram:852:11)
at Socket. (/opt/iobroker/node_modules/iobroker.sma-em/main.js:200:12)
at Socket.onListening (node:dgram:255:7)
at Socket.emit (node:events:513:28)
at startListening (node:dgram:181:10)
at node:dgram:369:7
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-05-07 05:03:38.058 - error: sma-em.0 (4999) Exception-Code: EADDRINUSE: addMembership EADDRINUSE
2023-05-07 05:03:38.087 - info: sma-em.0 (4999) cleaned everything up...
2023-05-07 05:03:38.089 - info: sma-em.0 (4999) terminating
2023-05-07 05:03:38.092 - warn: sma-em.0 (4999) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-05-07 05:03:38.094 - info: sma-em.0 (4999) UDP Socket closed ...
2023-05-07 05:03:38.753 - error: host.tims-pi1 instance system.adapter.sma-em.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-05-07 05:03:38.755 - info: host.tims-pi1 Restart adapter system.adapter.sma-em.0 because enabled
2023-05-07 05:03:38.755 - warn: host.tims-pi1 Do not restart adapter system.adapter.sma-em.0 because restart loop detected
```

**Comment by pdbjjens** [comment]
@ticaki 
Probleme mit Docker und Multicast sind schon öfter aufgetaucht (z.B. #541 ).
Es wird auch im iobroker/docker https://hub.docker.com/r/buanet/iobroker erwähnt.
Dort wird Umstellung auf MACVLAN empfohlen.
Ein user hat offenbar durch Umstellung auf "Host" networking das Problem in den Griff bekommen.
https://github.com/iobroker-community-adapters/ioBroker.sma-em/issues/371#issuecomment-1100135257

**Comment by pdbjjens** [comment]
@ticaki 
Ist das Problem durch Umstellung der Docker networking Konfiguration (wie oben von mir beschrieben) mittlerweile gelöst?

**Comment by ticaki** [comment]
Ich kenne mich mit docker nicht genug aus dafür, habe aber aus Auslastungsgründen Scrypted auf einen neuen PI4 verschoben. Somit läuft kein Docker mehr auf dem iobroker PI4 und alles ist für mich gut.

**Comment by pdbjjens** [comment]
@mcm1957 , @DutchmanNL 
Offenbar wird der Fehler EADDRINUSE

`2023-05-07 05:03:38.046 - info: sma-em.0 (4999) Listen via UDP on Device veth41362bb with IP 169.254.120.116 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.047 - info: sma-em.0 (4999) Listen via UDP on Device veth41362bb with IP 169.254.246.139 on Port 9522 for Multicast IP 239.12.255.254
2023-05-07 05:03:38.053 - error: sma-em.0 (4999) uncaught exception: addMembership EADDRINUSE`

dadurch ausgelöst, dass demselben Interface veth41362bb zwei local-link IP-Adressen zugewiesen sind. Sowas kommt anscheinend bei Docker vor und ist zulässig. 

Auch ist mir unklar, warum sma-em an einem bridge-Interface lauschen sollte.

`2023-05-07 05:03:38.045 - info: sma-em.0 (4999) Listen via UDP on Device br-e5c20c4ceb49 with IP 172.18.0.1 on Port 9522 for Multicast IP 239.12.255.254`

Daher stellt sich mir die Frage, ob es für den sma-em überhaupt Sinn macht, wie bisher an alle vorhandenen Netzwerk-Interfaces zu binden oder ob es nicht besser wäre, bei der Adapter-Config eine Option (select-box) einzuführen, bei der der Benutzer aus einer Liste aller vorhandenen IPs dasjenige Netzwerk auswählen kann, an dem der fragliche EM oder SHM hängt.
Sollten mehrere EMs in unterschiedlichen Netzen überwacht werden müssen, so müsste eine zweite Instanz erzeugt werden.
Das wäre für den Benutzer zwar etwas schwieriger, und ein "breaking change", würde aber helfen um Probleme wie dieses und auch andere wie z.B. in #110 oder #117 zu vermeiden. Der Wunsch nach "auswählbaren" Netzwerken kam schon öfter.

Eine Alternative wäre, vor dem addMembership alle bridge-Interfaces und virtual Interfaces auszublenden und nur die verbleibenden "echten " Interfaces hinzuzufügen. Dabei habe ich aber zur Zeit keine Idee, wie ich die bridge und virtual Interfaces elegant identifizieren und filtern könnte. 

Was meint Ihr dazu? Wessen Expertise könnte/sollte  man noch dazu einholen?

**Comment by mcm1957** [comment]
Vorweg:
- ich kenn mich mit Docker NULL aus
- ich hab  nur marginale IPv6 Kenntnisse
- ich kenn den Adapter nicht bzw. kenn seine Funktion nicht

Und damit mein Input:
Ich glaube gelesen zu haben, dass es durchaus zulässig ist einem Interface mehrerer unterschiedliche Addressen zuzuweisen.

Meines Erachtens könnte man das Problem so lösen, dass man entweder sicherstellt, dass man nur einmal an ein Device connected oder wie du vorgeschlagen hast, das Device / IP auswählbar macht. Im Falle der Auswahl würde ich allerdings anbieten an eine spezielle Address oder an alle verfügbaren Addressen anzubinden. Dies unterstützt m.W. nach auch der IP Typ der jsonConfig natiy - muss aber bei anderer Konfig auch umsetzbar sein. Siehe z.,B. admin Adapter:

![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/28575778/fffe00f3-1d2f-4491-9641-f66eda7c97c7)

Wenn man "alle" auch auswählbar macht, waäre das m.E: nicht mal breaking.  

Ansonsten, stell die Frage mal in Telegram. Da gibts sicher kompetente Teilnehmer. Insbesondere Apollon77 hat sich mit Netzwerk und IPv6 schon wegen Metter intensiov beschäftigt.

**Comment by ticaki** [comment]
Noch ein Update dazu:

Wenn man einem dev z.B. eth0 mehrere Ips zuweist kommt ebenfalls:#



```
sma-em.0 | 2023-07-01 15:50:31.557 | error | Exception-Code: EADDRINUSE: addMembership EADDRINUSE
-- | -- | -- | --
sma-em.0 | 2023-07-01 15:50:31.556 | error | Error: addMembership EADDRINUSE at Socket.addMembership (node:dgram:852:11) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sma-em/main.js:200:12) at Socket.onListening (node:dgram:255:7) at Socket.emit (node:events:513:28) at startListening (node:dgram:181:10) at node:dgram:369:7 at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
sma-em.0 | 2023-07-01 15:50:31.554 | error | uncaught exception: addMembership EADDRINUSE
```

Zuweisung sah so aus:
/etc/dhcpcd.exit-hook

```
#add secondary IP address
if [ "$reason" = "PREINIT" ]; then
        sudo ip -4 addr add 192.168.179.1/23 dev eth0 label eth0:1
        sudo ip -4 addr add 192.168.179.2/23 dev eth0 label eth0:2
        sudo ip -4 addr add 192.168.179.3/23 dev eth0 label eth0:3
        sudo ip -4 addr add 192.168.179.4/23 dev eth0 label eth0:4
        exit 0
fi
```

**Comment by pdbjjens** [comment]
@ticaki 
Danke für Deinen PR #581 
Ich hatte auch schon darüber nachgedacht, den Fehler im Adapter abzufangen und damit automatisch nur ein Netzwerk dieses Interfaces zu verbinden. Das löst sicher Dein issue und den Adapterabsturz. Aber da mit dieser Methode immer nur die erste gefundene IP eines Devices hinzugefügt wird, würde es möglicherweise das "falsche" sein (d.h. der user möchte gerne auf einem anderen Netzwerk lauschen lassen als dem ersten). Daher wäre eine Benutzerauswahl weiterhin erforderlich.
Da das aber eine größere Änderung bedeutet, tendiere ich dazu, Deinen PR zu akzeptieren um wenigstens den Adapterabsturz zu vermeiden und ein Bugfix release herausgeben. Die Benutzerauswahl würde dann erst in einem nächsten major Release erfolgen. Einverstanden @mcm1957 @DutchmanNL ?

**Comment by mcm1957** [comment]
Jede Verbesserung ist aus meiner Sicht ok.
Andonsten jann ich nicht viel beitragen da ich den Afapter nicht i. Detail kenne.

**Comment by ticaki** [comment]
@pdbjjens

```
sma-em.0 | 2023-07-01 17:22:52.219 | info | Drop Device eth0:3 with IP 192.168.179.3
sma-em.0 | 2023-07-01 17:22:52.218 | info | Drop Device eth0:2 with IP 192.168.179.2
sma-em.0 | 2023-07-01 17:22:52.217 | info | Drop Device eth0:1 with IP 192.168.179.1
sma-em.0 | 2023-07-01 17:22:52.214 | info | Listen via UDP on Device eth0 with IP 192.168.178.96 on Port 9522 for Multicast IP 239.12.255.254
```
lt. dieser Logausgabe sollte er nicht nur das erste nehmen, weiß es aber nicht. Ich guck mal ob das blöde wlan ans laufen bekomme, das sollte nach eth0 einsortiert sein, wird mir trotz tausendmal einstellen vom Ländercode von rfkill abgeschossen.

**Comment by ticaki** [comment]
Alles gut, er geht jedes device durch und nimmt auch welche die hinter den Drops kommen. Drops vielleicht durch Ignore ersetzen.



```
sma-em.0 | 2023-07-02 12:05:54.901 | info | Listen via UDP on Device wlan0 with IP 169.254.132.3 on Port 9522 for Multicast IP 239.12.255.254
-- | -- | -- | --
sma-em.0 | 2023-07-02 12:05:54.900 | info | Drop Device eth0:4 with IP 192.168.179.4
sma-em.0 | 2023-07-02 12:05:54.900 | info | Drop Device eth0:3 with IP 192.168.179.3
sma-em.0 | 2023-07-02 12:05:54.899 | info | Drop Device eth0:2 with IP 192.168.179.2
sma-em.0 | 2023-07-02 12:05:54.897 | info | Drop Device eth0:1 with IP 192.168.179.1
sma-em.0 | 2023-07-02 12:05:54.894 | info | Listen via UDP on Device eth0 with IP 192.168.178.96 on Port 9522 for Multicast IP 239.12.255.254
```

**Comment by pdbjjens** [comment]
@ticaki 
Danke für den zusätzlichen Test. So sollte es auch sein. Meine Einschränkung oben bezog sich darauf, dass ein user evtl. nicht das erste Netzwerk eines Devices mit mehreren IPs auswählen möchte, sondern eines der folgenden. Die übrigen Devices mit nur einer IP erzeugen ja keine Fehler und werden wie bisher in der for-Schleife der Reihe nach hinzugefügt.

**Comment by ticaki** [comment]
ok, das hab ich falsch verstanden, dafür gehts wlan jetzt :)

**Comment by pdbjjens** [comment]
@ticaki 
Ich arbeite an der Benutzerauswahl für die Network Interface IP. Ich würde mich sehr freuen, wenn Du die aktuelle Version auf GitHub in Deiner Umgebung testen würdest. Ich habe kein System bei dem ich die Benutzerauswahl von IPs bei Interfaces mit Mehrfach-IPs testen könnte. Dein PR ist bereits drin. Die neue Interface-Auswahl ist auf dem Config-Panel "Multicast-Settings" zu finden. Falls sonst noch was auffällt oder es Änderungswünsche gibt bitte gerne melden.

**Comment by ticaki** [comment]
Hab die letzte upload Meldung drin gelassen damit du nen Anfang hast. Läuft bis jetzt bestens. Hab 5 von 7 ausprobiert. Nur eines würde ich mir dann noch wünschen:

```
2023-07-05 19:03:05.818 - info: sma-em.0 (12690) starting. Version 0.7.0 (non-npm: iobroker-community-adapters/ioBroker.sma-em#7c260c581710e67e839e881d12c3df05f2192665) in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.1, js-controller: 5.0.6
--
2023-07-05 19:03:05.910 - info: sma-em.0 (12690) Details L1 false Details L2 false Details L3 false Extended Mode true RealTime Interval 1 non-Realtime Interval 30 Language: de

```
Wenn hier eine Warnmeldung im Log kommen würde mit kein Homemanager auf ausgewähltem Netzwerkinterface gefunden. Brauche ich zwar nicht, aber ich kenne Leute oh gott :)

`2023-07-05 18:55:32.280 - info: host.tims-pi1 iobroker Update "system.adapter.sma-em.0"
2023-07-05 18:55:32.290 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 (force=false, process=true)
2023-07-05 18:55:32.296 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 send kill signal
2023-07-05 18:55:32.296 - info: sma-em.0 (21218) Got terminate signal TERMINATE_YOURSELF
2023-07-05 18:55:32.309 - info: sma-em.0 (21218) cleaned everything up...
2023-07-05 18:55:32.312 - info: sma-em.0 (21218) terminating
2023-07-05 18:55:32.314 - info: sma-em.0 (21218) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-07-05 18:55:32.315 - info: sma-em.0 (21218) UDP Socket closed ...
2023-07-05 18:55:32.816 - info: sma-em.0 (21218) terminating
2023-07-05 18:55:32.895 - info: host.tims-pi1 instance system.adapter.sma-em.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-07-05 18:55:33.310 - info: host.tims-pi1 iobroker exit 0
2023-07-05 18:55:35.378 - info: host.tims-pi1 instance system.adapter.sma-em.0 started with pid 10918
2023-07-05 18:55:38.007 - info: sma-em.0 (10918) starting. Version 0.7.0 (non-npm: iobroker-community-adapters/ioBroker.sma-em#7c260c581710e67e839e881d12c3df05f2192665) in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.1, js-controller: 5.0.6
2023-07-05 18:55:38.122 - error: sma-em.0 (10918) Own IP is empty - please check instance configuration of sma-em.0
2023-07-05 18:56:10.797 - info: sonoff.0 (20572) Client [NOUS 02] reconnected. Old secret 1688544299364_4719. New secret 1688576170797_211
2023-07-05 18:58:07.256 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 (force=false, process=true)
2023-07-05 18:58:07.262 - info: sma-em.0 (10918) Got terminate signal TERMINATE_YOURSELF
2023-07-05 18:58:07.267 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 send kill signal
2023-07-05 18:58:07.268 - info: sma-em.0 (10918) cleaned everything up...
2023-07-05 18:58:07.272 - info: sma-em.0 (10918) terminating
2023-07-05 18:58:07.275 - info: sma-em.0 (10918) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-07-05 18:58:07.778 - info: sma-em.0 (10918) terminating
2023-07-05 18:58:07.906 - info: host.tims-pi1 instance system.adapter.sma-em.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-07-05 18:58:10.345 - info: host.tims-pi1 instance system.adapter.sma-em.0 started with pid 11675
2023-07-05 18:58:12.927 - info: sma-em.0 (11675) starting. Version 0.7.0 (non-npm: iobroker-community-adapters/ioBroker.sma-em#7c260c581710e67e839e881d12c3df05f2192665) in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.1, js-controller: 5.0.6
2023-07-05 18:58:13.025 - info: sma-em.0 (11675) Details L1 false Details L2 false Details L3 false Extended Mode true RealTime Interval 1 non-Realtime Interval 30 Language: de
2023-07-05 18:58:13.028 - info: sma-em.0 (11675) Listen via UDP on Network Interface eth0:1 with IP 192.168.179.1 on Port 9522 for Multicast IP 239.12.255.254
2023-07-05 18:58:13.031 - info: sma-em.0 (11675) Skip Network Interface eth0:2 with IP 192.168.179.2
2023-07-05 18:58:13.032 - info: sma-em.0 (11675) Skip Network Interface eth0:3 with IP 192.168.179.3
2023-07-05 18:58:13.033 - info: sma-em.0 (11675) Skip Network Interface eth0:4 with IP 192.168.179.4
2023-07-05 18:58:13.034 - info: sma-em.0 (11675) Skip Network Interface eth0 with IP 192.168.178.96
2023-07-05 18:58:15.100 - info: sma-em.0 (11675) New device discovered: Sunny Home Manager 2.0 S/N: 3015986450 with IP/port: 192.168.178.128/49843 message rate: 1/sec
2023-07-05 18:58:38.616 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 (force=false, process=true)
2023-07-05 18:58:38.620 - info: host.tims-pi1 stopInstance system.adapter.sma-em.0 send kill signal
2023-07-05 18:58:38.622 - info: sma-em.0 (11675) Got terminate signal TERMINATE_YOURSELF
2023-07-05 18:58:38.625 - info: sma-em.0 (11675) cleaned everything up...
2023-07-05 18:58:38.627 - info: sma-em.0 (11675) terminating
2023-07-05 18:58:38.630 - info: sma-em.0 (11675) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-07-05 18:58:38.632 - info: sma-em.0 (11675) UDP Socket closed ...
2023-07-05 18:58:39.133 - info: sma-em.0 (11675) terminating
2023-07-05 18:58:39.277 - info: host.tims-pi1 instance system.adapter.sma-em.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-07-05 18:58:41.760 - info: host.tims-pi1 instance system.adapter.sma-em.0 started with pid 11724
2023-07-05 18:58:44.446 - info: sma-em.0 (11724) starting. Version 0.7.0 (non-npm: iobroker-community-adapters/ioBroker.sma-em#7c260c581710e67e839e881d12c3df05f2192665) in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.1, js-controller: 5.0.6
2023-07-05 18:58:44.552 - info: sma-em.0 (11724) Details L1 false Details L2 false Details L3 false Extended Mode true RealTime Interval 1 non-Realtime Interval 30 Language: de
2023-07-05 18:58:44.554 - info: sma-em.0 (11724) Listen via UDP on Network Interface eth0 with IP 192.168.178.96 on Port 9522 for Multicast IP 239.12.255.254
2023-07-05 18:58:46.093 - info: sma-em.0 (11724) New device discovered: Sunny Home Manager 2.0 S/N: 3015986450 with IP/port: 192.168.178.128/49843 message rate: 1/sec`

**Comment by pdbjjens** [comment]
@ticaki 
Danke für Deinen Test und Deine Anregung bzgl. der fehlenden Fehlermeldung wenn ein user 127.0.0.1 als Netzwerk Interface IP auswählt. 
Es wäre am besten, wenn in der Auswahlbox auf der Config Seite die 127.0.0.1 überhaupt nicht angeboten würde, denn es macht natürlich keinerlei Sinn, wenn der Adapter auf einem lokalen loopback interface auf multicasts lauscht.
@mcm1957 
Siehst Du eine Möglichkeit, noch einen key "noInternal" im jsonConfig ip Control einbauen zu lassen (analog zu den keys onlyIP4 usw.) womit dann die lokalen loopback-Adressen in der Auswahlbox ausgeblendet würden?

**Comment by mcm1957** [comment]
_Siehst Du eine Möglichkeit, noch einen key "noInternal" im jsonConfig ip Control einbauen zu lassen (analog zu den keys onlyIP4 usw.) womit dann die lokalen loopback-Adressen in der Auswahlbox ausgeblendet würden?_

Schreib ein entsprechendes issue im iobroker.admin repo.
Keine Ahnung welcher Aufwand das ist (schätze aber gering) und wann wer dafür Zeit hat.

**Comment by pdbjjens** [comment]
@ticaki 
Ich habe jetzt erstmal eine Fehlermeldung eingebaut, die protokolliert wird, wenn der Benutzer die Loopback IP 127.0.0.1 auswählt. 
 Um die loopback IPs erst gar nicht zur Anzeige in der Auswahlbox zu bringen, ist eine Änderung im iobroker Admin erforderlich. Ob und wann das implementiert wird ist unbekannt. (Bei 140 open issues kann das vermutlich noch dauern)
Ich würde mich freuen, wenn Du die neuste GitHub Version testen würdest, ob das zunächst mal so ausreichend ist.
@mcm1957 
Ich habe in Feature request issue an iobroker/admin bzgl. des ip control gestellt [https://github.com/ioBroker/ioBroker.admin/issues/1971](https://github.com/ioBroker/ioBroker.admin/issues/1971).

**Comment by ticaki** [comment]
Läuft alles so wie erwartet.

**Comment by pdbjjens** [comment]
Fixed with release v1.0.0 ( #611  )
